- name: install nftables
  apt:
    name: nftables
    state: latest

- name: remove default nft conf file
  command: "rm /etc/nftables.conf"

- name: copy nft file
  ansible.builtin.copy:
    src: ./nftables.conf
    dest: /etc/nftables.conf

- name: load nft rules
  command: "/sbin/nft -f /etc/nftables.conf"
