- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Update apt and install docker
  apt:
    name: 
    - docker-ce 
    - docker-ce-cli
    - containerd.io 
    - docker-buildx-plugin
    - docker-compose-plugin
    state: latest
    update_cache: true

- name: create composer dir
  file:
    path: /root/wordpress-compose
    state: directory 

- name: copy compose file
  ansible.builtin.copy:
    src: ./docker-compose.yaml
    dest: /root/wordpress-compose/docker-compose.yaml

#- name: run containers
#  command: 'docker-compose up -d'
#  args:
#    chdir: '/root/wordpress-compose'

- name: Run containers with docker-compose
  community.general.docker_compose:
    project_src: '/root/wordpress-compose'
    state: started

