---
- hosts: targets
  become: true
  #vars:
   # container_count: 1
    #default_container_name: $CONTAINER_NAME
    #default_container_image: debian
    #default_container_command: sleep 1
  
  roles:
    - docker
    - nftables

- name: create composer dir
  file:
    path: /root/wordpress-compose
    state: directory 

- name: copy compose file
  ansible.builtin.copy:
    src: ./docker-compose.yaml
    dest: /root/wordpress-compose/docker-compose.yaml

- name: Run containers with docker-compose
  community.general.docker_compose:
    project_src: '/root/wordpress-compose'
    state: started

    

