- name: stop docker service 
  ansible.builtin.service
  name: 
    - docker.service
    - docker.socket
  state: stoped 

- name: run rootless installation script
  shell: /usr/bin/dockerd-rootless-setuptool.sh install
  become: true
  become_user: changeme 

- name: start docker service 
  ansible.builtin.service
  name: 
    - docker.service
    - docker.socket
  state: restarted 
