---
- hosts: targets
  become: true
  roles:
    - docker
  tasks:
  
  - name: create compose dir
    file:
      path: /root/wordpress-compose
      state: directory 

  - name: copy compose file
    ansible.builtin.copy:
      src: templates/docker-compose.wp.j2.yml
      dest: /root/wordpress-compose/docker-compose.yml

  - name: Run containers with docker-compose
    community.docker.docker_compose_v2:
      project_src: '/root/wordpress-compose'
      state: present 
      tags: start-wp
