---
- hosts: localhost
  become: true
  tasks:
  
  - name: create dirs
    ansible.builtin.file:
      path: /root/semaui/.ssh
      state: directory
      owner: 1001
      group: root

  - name: create ssh keys
    community.crypto.openssh_keypair:
      path: /root/semaui/.ssh/id_ed25519
      type: ed25519
      owner: 1001
      group: root
