---
- hosts: localhost
  become: true
  tasks:
  
  - name: create dirs
    ansible.builtin.file:
      path: /root/semaui/.ssh
      state: directory
      owner: 1001
      group: root
    
  - name: create ssh keys
    community.crypto.openssh_keypair:
      path: /root/semaui/.ssh/id_ed25519
      type: ed25519
      owner: 1001
      group: root

  - name: copy compose file
    ansible.builtin.copy:
      src: files/docker-compose.yml
      dest: /root/semaui/

  - name: build and start containers
    community.docker.docker_compose_v2:
      project_src: /root/semaui/
    
